name: "🛠️ Custom Issue"
description: "For requests or suggestions that don't fit into bug, feature, or docs"
title: "[Custom] <short-title>"
labels: ["custom", "needs-triage"]
assignees: []

body:
  - type: checkboxes
    id: search
    attributes:
      label: "🔍 Have You Searched Existing Issues?"
      options:
        - label: "I have searched the existing issues to avoid duplicates"
          required: true

  - type: textarea
    id: description
    attributes:
      label: "🔍 Issue Description"
      description: "Describe the issue or suggestion in detail. Include any relevant context."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "💡 Expected behavior"
      description: "Describe the expected behavior."
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "🙌 Contributor Checklist"
      options:
        - label: "I agree to follow this project's Code of Conduct"
