export interface DrugSeed {
    id: string; // unique identifier used for cache key prefix/lookup
    genericName: string;
    brandNames: string[];
}

export const hotDrugs: DrugSeed[] = [
    { id: "paracetamol", genericName: "Paracetamol", brandNames: ["Crocin", "Dolo 650", "Calpol"] },
    { id: "amoxicillin", genericName: "Amoxicillin", brandNames: ["Mox", "Amoxil", "Novamox"] },
    { id: "ibuprofen", genericName: "Ibuprofen", brandNames: ["Brufen", "Ibugesic"] },
    { id: "metformin", genericName: "Metformin", brandNames: ["Glycomet", "Obimet"] },
    {
        id: "atorvastatin",
        genericName: "Atorvastatin",
        brandNames: ["Lipivas", "Atorva", "Tonact"],
    },
    { id: "amlodipine", genericName: "Amlodipine", brandNames: ["Amlopin", "Stamlo"] },
    { id: "pantoprazole", genericName: "Pantoprazole", brandNames: ["Pan", "Pantocid"] },
    { id: "omeprazole", genericName: "Omeprazole", brandNames: ["Omez"] },
    { id: "azithromycin", genericName: "Azithromycin", brandNames: ["Azee", "Azithral"] },
    { id: "cetirizine", genericName: "Cetirizine", brandNames: ["Cetzine", "Okacet"] },
    { id: "levocetirizine", genericName: "Levocetirizine", brandNames: ["L-Hist", "Levocet"] },
    { id: "montelukast", genericName: "Montelukast", brandNames: ["Montek", "Telekast"] },
    { id: "ranitidine", genericName: "Ranitidine", brandNames: ["Rantac", "Aciloc"] },
    { id: "domperidone", genericName: "Domperidone", brandNames: ["Domstal"] },
    { id: "losartan", genericName: "Losartan", brandNames: ["Covance", "Losacar"] },
    { id: "telmisartan", genericName: "Telmisartan", brandNames: ["Telma", "Tazloc"] },
    { id: "ciprofloxacin", genericName: "Ciprofloxacin", brandNames: ["Ciplox", "Cipro"] },
    { id: "norfloxacin", genericName: "Norfloxacin", brandNames: ["Norflox"] },
    { id: "ofloxacin", genericName: "Ofloxacin", brandNames: ["Oflox", "Zanocin"] },
    { id: "metronidazole", genericName: "Metronidazole", brandNames: ["Flagyl", "Metrogyl"] },
    { id: "diclofenac", genericName: "Diclofenac", brandNames: ["Voveran", "Dynapar"] },
    { id: "aceclofenac", genericName: "Aceclofenac", brandNames: ["Zerodol", "Hifenac"] },
    { id: "tramadol", genericName: "Tramadol", brandNames: ["Ultracet", "Tramazac"] },
    { id: "gabapentin", genericName: "Gabapentin", brandNames: ["Gabapin", "Neurontin"] },
    { id: "pregabalin", genericName: "Pregabalin", brandNames: ["Lyrica", "Pregab"] },
    { id: "salbutamol", genericName: "Salbutamol", brandNames: ["Asthalin"] },
    { id: "budesonide", genericName: "Budesonide", brandNames: ["Budecort", "Pulmicort"] },
    { id: "levothyroxine", genericName: "Levothyroxine", brandNames: ["Thyronorm", "Eltroxin"] },
    { id: "glimepiride", genericName: "Glimepiride", brandNames: ["Amaryl", "Glimy"] },
    { id: "gliclazide", genericName: "Gliclazide", brandNames: ["Reclimet", "Diamicron"] },
    { id: "rosuvastatin", genericName: "Rosuvastatin", brandNames: ["Rosuvas", "Crevast"] },
    { id: "clopidogrel", genericName: "Clopidogrel", brandNames: ["Clopilet", "Deplatt"] },
    { id: "aspirin", genericName: "Aspirin", brandNames: ["Ecosprin", "Loprin"] },
    { id: "spironolactone", genericName: "Spironolactone", brandNames: ["Aldactone"] },
    { id: "furosemide", genericName: "Furosemide", brandNames: ["Lasix"] },
    { id: "hydrochlorothiazide", genericName: "Hydrochlorothiazide", brandNames: ["Aquazide"] },
    {
        id: "calcium_carbonate",
        genericName: "Calcium Carbonate",
        brandNames: ["Shelcal", "Calcirol"],
    },
    { id: "vitamin_d3", genericName: "Vitamin D3", brandNames: ["Calcirol", "D3-Must"] },
    { id: "folic_acid", genericName: "Folic Acid", brandNames: ["Folvite"] },
    { id: "iron_sucrose", genericName: "Iron Sucrose", brandNames: ["Orofer"] },
    { id: "zinc", genericName: "Zinc", brandNames: ["Zincovit"] },
    { id: "multivitamin", genericName: "Multivitamin", brandNames: ["Becosules", "Cobadex"] },
    {
        id: "augmentin",
        genericName: "Amoxicillin-Clavulanic Acid",
        brandNames: ["Augmentin", "Clavam"],
    },
    { id: "pipzo", genericName: "Piperacillin-Tazobactam", brandNames: ["Tazact", "Pipzo"] },
    { id: "monocef", genericName: "Ceftriaxone", brandNames: ["Monocef", "Keftragard"] },
    { id: "meropenem", genericName: "Meropenem", brandNames: ["Meronem"] },
    { id: "linezolid", genericName: "Linezolid", brandNames: ["Lizoforce"] },
    { id: "ondansetron", genericName: "Ondansetron", brandNames: ["Emset", "Zofran"] },
    { id: "itraconazole", genericName: "Itraconazole", brandNames: ["Sporanox", "Canditral"] },
    { id: "fluconazole", genericName: "Fluconazole", brandNames: ["Forcan", "Syscan"] },
];
