-- =============================================================================
-- SahiDawa — CDSCO reference fuzzy matching with pg_trgm
-- =============================================================================
-- Keeps the authoritative CDSCO brand registry in Postgres so the ETL validator
-- can delegate cross-registry fuzzy lookups to Supabase instead of doing a
-- Python-level global RapidFuzz scan.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS public.cdsco_reference (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_name TEXT NOT NULL,
  firm_name TEXT NOT NULL DEFAULT '',
  brand_name_normalized TEXT NOT NULL,
  firm_name_normalized TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_cdsco_reference_normalized_unique
  ON public.cdsco_reference (brand_name_normalized, firm_name_normalized);

CREATE INDEX IF NOT EXISTS idx_cdsco_reference_brand_name_trgm
  ON public.cdsco_reference
  USING gin (brand_name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_cdsco_reference_brand_name_normalized_trgm
  ON public.cdsco_reference
  USING gin (brand_name_normalized gin_trgm_ops);

CREATE OR REPLACE FUNCTION public.find_cdsco_fuzzy_match(
  query_brand_name TEXT,
  query_manufacturer TEXT DEFAULT '',
  match_count INTEGER DEFAULT 1,
  min_similarity DOUBLE PRECISION DEFAULT 0.2
)
RETURNS TABLE (
  brand_name TEXT,
  manufacturer TEXT,
  product_score DOUBLE PRECISION,
  manufacturer_score DOUBLE PRECISION,
  match_score DOUBLE PRECISION
) AS $$
DECLARE
  normalized_query_brand_name TEXT;
  normalized_query_manufacturer TEXT;
  effective_min_similarity DOUBLE PRECISION;
BEGIN
  normalized_query_brand_name := lower(btrim(COALESCE(query_brand_name, '')));
  normalized_query_manufacturer := lower(btrim(COALESCE(query_manufacturer, '')));

  IF normalized_query_brand_name = '' THEN
    RETURN;
  END IF;

  effective_min_similarity :=
    LEAST(GREATEST(COALESCE(min_similarity, 0.2), 0.0), 1.0);

  PERFORM set_config(
    'pg_trgm.similarity_threshold',
    effective_min_similarity::TEXT,
    TRUE
  );

  RETURN QUERY
  WITH ranked_brand_matches AS (
    SELECT
      r.brand_name AS candidate_brand_name,
      r.firm_name AS candidate_firm_name,
      (
        similarity(r.brand_name_normalized, normalized_query_brand_name) * 100.0
      )::DOUBLE PRECISION AS candidate_product_score,
      (
        similarity(
          r.firm_name_normalized,
          normalized_query_manufacturer
        ) * 100.0
      )::DOUBLE PRECISION AS candidate_manufacturer_score
    FROM public.cdsco_reference AS r
    WHERE r.brand_name_normalized % normalized_query_brand_name
    ORDER BY r.brand_name_normalized <-> normalized_query_brand_name
    LIMIT GREATEST(match_count, 1) * 10
  ),
  scored_matches AS (
    SELECT
      ranked_brand_matches.candidate_brand_name,
      ranked_brand_matches.candidate_firm_name,
      ranked_brand_matches.candidate_product_score,
      ranked_brand_matches.candidate_manufacturer_score,
      (
        0.7 * ranked_brand_matches.candidate_product_score
        + 0.3 * ranked_brand_matches.candidate_manufacturer_score
      )::DOUBLE PRECISION AS candidate_match_score
    FROM ranked_brand_matches
  )
  SELECT
    scored_matches.candidate_brand_name AS brand_name,
    scored_matches.candidate_firm_name AS manufacturer,
    scored_matches.candidate_product_score AS product_score,
    scored_matches.candidate_manufacturer_score AS manufacturer_score,
    scored_matches.candidate_match_score AS match_score
  FROM scored_matches
  ORDER BY
    scored_matches.candidate_match_score DESC,
    scored_matches.candidate_product_score DESC
  LIMIT GREATEST(match_count, 1);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

COMMENT ON TABLE public.cdsco_reference IS
  'Authoritative CDSCO brand/manufacturer reference rows synced by the ETL pipeline.';

COMMENT ON FUNCTION public.find_cdsco_fuzzy_match(
  TEXT,
  TEXT,
  INTEGER,
  DOUBLE PRECISION
) IS 'Returns CDSCO reference brand-name fuzzy matches ranked with pg_trgm product similarity and manufacturer similarity.';
